### ISSUE TITLE
confusing about the Cascade Preprocessing

### ISSUE THREAD

**Issue by pandayuanyu** [PKU-YuanGroup/MagicTime#9]
Hi authors, thank you for your nice work! 

I am confused about the Cascade Preprocessing present in the paper. Could you explain more about the motivations as well as the definition of transiation point? Thanks.

**Comment by SHYuanBest** [comment]
Thanks for your interest! Transition point refers to the place where the content or picture changes significantly during video playback. This change can be a scene switch, an angle change, a time jump or a transition between different shots. It is usually used to attract the audience's attention or show different perspectives.
Since our training data is crawled from video platforms, these videos are originally intended to serve the audience, so there will be a lot of transitions. It is possible that a person is talking one second and a flower is blooming the next second. Since training MagicTime requires clean data, we use Cascade Preprocessing to automatically split the data according to transition points to maintain the consistency of video semantics.

**Comment by pandayuanyu** [comment]
> Thanks for your interest! Transition point refers to the place where the content or picture changes significantly during video playback. This change can be a scene switch, an angle change, a time jump or a transition between different shots. It is usually used to attract the audience's attention or show different perspectives. Since our training data is crawled from video platforms, these videos are originally intended to serve the audience, so there will be a lot of transitions. It is possible that a person is talking one second and a flower is blooming the next second. Since training MagicTime requires clean data, we use Cascade Preprocessing to automatically split the data according to transition points to maintain the consistency of video semantics.

Got you, thank you!
